
// AUTO GENERATED FILE FROM buildscript_versioning.py, DO NOT EDIT THIS FILE
#ifndef BUILD_NUMBER
  #define BUILD_NUMBER "17"
#endif
#ifndef VERSION
  #define VERSION "1.2.17 - 2020-04-03 22:28:25.299218"
#endif
#ifndef VERSION_SHORT
  #define VERSION_SHORT "1.2.17"
#endif
