
// AUTO GENERATED FILE FROM buildscript_versioning.py, DO NOT EDIT THIS FILE
#ifndef BUILD_NUMBER
  #define BUILD_NUMBER "14"
#endif
#ifndef VERSION
  #define VERSION "1.2.14 - 2020-04-03 14:51:23.689972"
#endif
#ifndef VERSION_SHORT
  #define VERSION_SHORT "1.2.14"
#endif
