
    // AUTO GENERATED FILE FROM buildscript_versioning.py, DO NOT EDIT THIS FILE
    #ifndef BUILD_NUMBER
      #define BUILD_NUMBER "30"
    #endif
    #ifndef VERSION
      #define VERSION "1.2.30 - 2020-04-09 23:07:35.161578"
    #endif
    #ifndef VERSION_SHORT
      #define VERSION_SHORT "1.2.30"
    #endif
    