name: GitHub Actions CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        python --version
    - name: Install submodules 
      run: |        
        git submodule update --init
    - name: Set lib extra dirs for CI
      run: |     
        sed -i 's,^lib_extra_dirs =.*$,lib_extra_dirs = /home/runner/work/smart_watch_winder/smart_watch_winder/arduino_bootstrapper/arduino_bootstrapper,' platformio.ini
        cat platformio.ini
    - name: Setup template config files
      run: |                
        cp /home/runner/work/smart_watch_winder/smart_watch_winder/arduino_bootstrapper/include/Secrets.h.template /home/runner/work/smart_watch_winder/smart_watch_winder/include/Secrets.h
        cp /home/runner/work/smart_watch_winder/smart_watch_winder/arduino_bootstrapper/include/Secrets.h.template /home/runner/work/smart_watch_winder/smart_watch_winder/arduino_bootstrapper/include/Secrets.h   
        cp /home/runner/work/smart_watch_winder/smart_watch_winder/include/Configuration.h /home/runner/work/smart_watch_winder/smart_watch_winder/arduino_bootstrapper/include/Configuration.h  
    - name: Run PlatformIO (watchwinder_1)
      run: platformio run -e watchwinder_1
    - name: Creating watchwinder_1 artifact from BIN file 
      uses: actions/upload-artifact@v1
      with:
        name: firmware_build_artifact_watchwinder_1.bin
        path: .pio/build/watchwinder_1/firmware.bin
    - name: Run PlatformIO (watchwinder_2)
      run: platformio run -e watchwinder_2
    - name: Creating watchwinder_2 artifact from BIN file 
      uses: actions/upload-artifact@v1
      with:
        name: firmware_build_artifact_watchwinder_2.bin
        path: .pio/build/watchwinder_2/firmware.bin
    - name: Run PlatformIO (watchwinder_3)
      run: platformio run -e watchwinder_3
    - name: Creating watchwinder_3 artifact from BIN file 
      uses: actions/upload-artifact@v1
      with:
        name: firmware_build_artifact_watchwinder_3.bin
        path: .pio/build/watchwinder_3/firmware.bin      
    - name: Run PlatformIO (watchwinder_4)
      run: platformio run -e watchwinder_4
    - name: Creating watchwinder_4 artifact from BIN file 
      uses: actions/upload-artifact@v1
      with:
        name: firmware_build_artifact_watchwinder_4.bin
        path: .pio/build/watchwinder_4/firmware.bin
    - name: Run PlatformIO (watchwinder_5)
      run: platformio run -e watchwinder_5
    - name: Creating watchwinder_5 artifact from BIN file 
      uses: actions/upload-artifact@v1
      with:
        name: firmware_build_artifact_watchwinder_5.bin
        path: .pio/build/watchwinder_5/firmware.bin
    - name: Run PlatformIO (watchwinder_6)
      run: platformio run -e watchwinder_6
    - name: Creating watchwinder_6 artifact from BIN file 
      uses: actions/upload-artifact@v1
      with:
        name: firmware_build_artifact_watchwinder_6.bin
        path: .pio/build/watchwinder_6/firmware.bin
